// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.AttachFile;
import com.cma.AttachFileDataOnDemand;
import com.cma.AttachFileIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AttachFileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttachFileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttachFileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AttachFileIntegrationTest: @Transactional;
    
    @Autowired
    AttachFileDataOnDemand AttachFileIntegrationTest.dod;
    
    @Test
    public void AttachFileIntegrationTest.testCountAttachFiles() {
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", dod.getRandomAttachFile());
        long count = AttachFile.countAttachFiles();
        Assert.assertTrue("Counter for 'AttachFile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttachFileIntegrationTest.testFindAttachFile() {
        AttachFile obj = dod.getRandomAttachFile();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to provide an identifier", id);
        obj = AttachFile.findAttachFile(id);
        Assert.assertNotNull("Find method for 'AttachFile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AttachFile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AttachFileIntegrationTest.testFindAllAttachFiles() {
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", dod.getRandomAttachFile());
        long count = AttachFile.countAttachFiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'AttachFile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AttachFile> result = AttachFile.findAllAttachFiles();
        Assert.assertNotNull("Find all method for 'AttachFile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AttachFile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttachFileIntegrationTest.testFindAttachFileEntries() {
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", dod.getRandomAttachFile());
        long count = AttachFile.countAttachFiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AttachFile> result = AttachFile.findAttachFileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AttachFile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AttachFile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttachFileIntegrationTest.testFlush() {
        AttachFile obj = dod.getRandomAttachFile();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to provide an identifier", id);
        obj = AttachFile.findAttachFile(id);
        Assert.assertNotNull("Find method for 'AttachFile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAttachFile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AttachFile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttachFileIntegrationTest.testMergeUpdate() {
        AttachFile obj = dod.getRandomAttachFile();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to provide an identifier", id);
        obj = AttachFile.findAttachFile(id);
        boolean modified =  dod.modifyAttachFile(obj);
        Integer currentVersion = obj.getVersion();
        AttachFile merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AttachFile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttachFileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", dod.getRandomAttachFile());
        AttachFile obj = dod.getNewTransientAttachFile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AttachFile' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AttachFile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AttachFileIntegrationTest.testRemove() {
        AttachFile obj = dod.getRandomAttachFile();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttachFile' failed to provide an identifier", id);
        obj = AttachFile.findAttachFile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AttachFile' with identifier '" + id + "'", AttachFile.findAttachFile(id));
    }
    
}
