// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.Children_profileDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Children_profileDataOnDemand_Roo_Configurable {
    
    declare @type: Children_profileDataOnDemand: @Configurable;
    
}
