// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.MapStudent;
import com.cma.MapStudentDataOnDemand;
import com.cma.Student;
import com.cma.StudentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MapStudentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MapStudentDataOnDemand: @Component;
    
    private Random MapStudentDataOnDemand.rnd = new SecureRandom();
    
    private List<MapStudent> MapStudentDataOnDemand.data;
    
    @Autowired
    StudentDataOnDemand MapStudentDataOnDemand.studentDataOnDemand;
    
    public MapStudent MapStudentDataOnDemand.getNewTransientMapStudent(int index) {
        MapStudent obj = new MapStudent();
        setInitStudent(obj, index);
        return obj;
    }
    
    public void MapStudentDataOnDemand.setInitStudent(MapStudent obj, int index) {
        Student initStudent = studentDataOnDemand.getSpecificStudent(index);
        obj.setInitStudent(initStudent);
    }
    
    public MapStudent MapStudentDataOnDemand.getSpecificMapStudent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MapStudent obj = data.get(index);
        Long id = obj.getId();
        return MapStudent.findMapStudent(id);
    }
    
    public MapStudent MapStudentDataOnDemand.getRandomMapStudent() {
        init();
        MapStudent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return MapStudent.findMapStudent(id);
    }
    
    public boolean MapStudentDataOnDemand.modifyMapStudent(MapStudent obj) {
        return false;
    }
    
    public void MapStudentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MapStudent.findMapStudentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MapStudent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MapStudent>();
        for (int i = 0; i < 10; i++) {
            MapStudent obj = getNewTransientMapStudent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
