// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.AttachFile;
import com.cma.Batch;
import com.cma.Student;
import com.cma.StudentDataOnDemand;
import com.cma.UserWeb;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect StudentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StudentDataOnDemand: @Component;
    
    private Random StudentDataOnDemand.rnd = new SecureRandom();
    
    private List<Student> StudentDataOnDemand.data;
    
    public Student StudentDataOnDemand.getNewTransientStudent(int index) {
        Student obj = new Student();
        setAllergiesSeaFood(obj, index);
        setAttachFile(obj, index);
        setBdField(obj, index);
        setBdUniversity(obj, index);
        setBdYear(obj, index);
        setBdateString(obj, index);
        setBeefFood(obj, index);
        setBirthdate(obj, index);
        setBuilding(obj, index);
        setCarBrand(obj, index);
        setCarColor(obj, index);
        setCarNo(obj, index);
        setChildrenBdateString(obj, index);
        setChildrenBirthday(obj, index);
        setChildrenCareer(obj, index);
        setChildrenFirstName(obj, index);
        setChildrenLastName(obj, index);
        setChildrenNationality(obj, index);
        setChildrenRace(obj, index);
        setChildrenReligion(obj, index);
        setCollboratorEmail(obj, index);
        setCollboratorFax(obj, index);
        setCollboratorFirstName(obj, index);
        setCollboratorFullName(obj, index);
        setCollboratorLastName(obj, index);
        setCollboratorLineId(obj, index);
        setCollboratorMobile(obj, index);
        setCollboratorPosition(obj, index);
        setCollboratorTel(obj, index);
        setCollboratorTel_2(obj, index);
        setCollboratorTitle(obj, index);
        setDataState(obj, index);
        setDistrict(obj, index);
        setDriverTel(obj, index);
        setEmail(obj, index);
        setEmail2(obj, index);
        setEnrollType(obj, index);
        setExtcollboratorTel(obj, index);
        setExthometel1(obj, index);
        setExthometel2(obj, index);
        setExtworktel1(obj, index);
        setExtworktel2(obj, index);
        setFacebook(obj, index);
        setFirstnameEn(obj, index);
        setFirstnameTh(obj, index);
        setFloor(obj, index);
        setFrontcollboratorFax(obj, index);
        setFrontcollboratorMobile(obj, index);
        setFrontcollboratorTel(obj, index);
        setFrontdriverTel(obj, index);
        setFronthomefax(obj, index);
        setFronthometel1(obj, index);
        setFronthometel2(obj, index);
        setFrontmobile1(obj, index);
        setFrontmobile2(obj, index);
        setFrontworkfax(obj, index);
        setFrontworktel1(obj, index);
        setFrontworktel2(obj, index);
        setFullNameEn(obj, index);
        setFullNameTh(obj, index);
        setGeneralFood(obj, index);
        setGroupName(obj, index);
        setHalalFood(obj, index);
        setHandyCap(obj, index);
        setHomeFullAddress(obj, index);
        setHomeNo(obj, index);
        setHomefax(obj, index);
        setHometel1(obj, index);
        setHometel1_2(obj, index);
        setHometel2(obj, index);
        setHometel2_2(obj, index);
        setIdcardNo(obj, index);
        setInstitutionBuilding(obj, index);
        setInstitutionDistrict(obj, index);
        setInstitutionEn(obj, index);
        setInstitutionFloor(obj, index);
        setInstitutionMooNo(obj, index);
        setInstitutionNo(obj, index);
        setInstitutionPostalCode(obj, index);
        setInstitutionProvince(obj, index);
        setInstitutionSoi(obj, index);
        setInstitutionStreet(obj, index);
        setInstitutionSubdistrict(obj, index);
        setInstitutionTh(obj, index);
        setJFood(obj, index);
        setJacketSize(obj, index);
        setLastcollboratorFax(obj, index);
        setLastcollboratorMobile(obj, index);
        setLastcollboratorTel(obj, index);
        setLastdriverTel(obj, index);
        setLasthomefax(obj, index);
        setLasthometel1(obj, index);
        setLasthometel2(obj, index);
        setLastmobile1(obj, index);
        setLastmobile2(obj, index);
        setLastnameEn(obj, index);
        setLastnameTh(obj, index);
        setLastworkfax(obj, index);
        setLastworktel1(obj, index);
        setLastworktel2(obj, index);
        setLineId(obj, index);
        setMarriedStatus(obj, index);
        setMdField(obj, index);
        setMdUniversity(obj, index);
        setMdYear(obj, index);
        setMiddlecollboratorFax(obj, index);
        setMiddlecollboratorMobile(obj, index);
        setMiddlecollboratorTel(obj, index);
        setMiddledriverTel(obj, index);
        setMiddlehomefax(obj, index);
        setMiddlehometel1(obj, index);
        setMiddlehometel2(obj, index);
        setMiddlemobile1(obj, index);
        setMiddlemobile2(obj, index);
        setMiddleworkfax(obj, index);
        setMiddleworktel1(obj, index);
        setMiddleworktel2(obj, index);
        setMobile1(obj, index);
        setMobile2(obj, index);
        setMooNo(obj, index);
        setNickname(obj, index);
        setOtherFood(obj, index);
        setPassportNo(obj, index);
        setPermission(obj, index);
        setPhdField(obj, index);
        setPhdUniversity(obj, index);
        setPhdYear(obj, index);
        setPhotoFileName(obj, index);
        setPlayGolf(obj, index);
        setPoloSize(obj, index);
        setPositionEn(obj, index);
        setPositionTh(obj, index);
        setPostalCode(obj, index);
        setProvince(obj, index);
        setReceiptDetailAddress(obj, index);
        setReceiptDetailName(obj, index);
        setRetireFlag(obj, index);
        setRopNo(obj, index);
        setSendingAddress(obj, index);
        setSex(obj, index);
        setSmoking(obj, index);
        setSoi(obj, index);
        setSpouseBdateString(obj, index);
        setSpouseBirthDay(obj, index);
        setSpouseCareer(obj, index);
        setSpouseFirstName(obj, index);
        setSpouseInstitution(obj, index);
        setSpouseLastName(obj, index);
        setSpouseNationality(obj, index);
        setSpouseRace(obj, index);
        setSpouseReligion(obj, index);
        setStreet(obj, index);
        setStudentClass(obj, index);
        setSubdistrict(obj, index);
        setSubmitProfile(obj, index);
        setTall(obj, index);
        setTaxId(obj, index);
        setTitleEn(obj, index);
        setTitleTh(obj, index);
        setTraingYear(obj, index);
        setTrainingClass(obj, index);
        setTrainingInstitute(obj, index);
        setTrainingName(obj, index);
        setUserWeb(obj, index);
        setVegeterianFood(obj, index);
        setVillage(obj, index);
        setWaist(obj, index);
        setWorkEmail(obj, index);
        setWorkFullAddress(obj, index);
        setWorkfax(obj, index);
        setWorktel1(obj, index);
        setWorktel1_2(obj, index);
        setWorktel2(obj, index);
        setWorktel2_2(obj, index);
        return obj;
    }
    
    public void StudentDataOnDemand.setAllergiesSeaFood(Student obj, int index) {
        Boolean allergiesSeaFood = true;
        obj.setAllergiesSeaFood(allergiesSeaFood);
    }
    
    public void StudentDataOnDemand.setAttachFile(Student obj, int index) {
        AttachFile attachFile = null;
        obj.setAttachFile(attachFile);
    }
    
    public void StudentDataOnDemand.setBdField(Student obj, int index) {
        String bdField = "bdField_" + index;
        obj.setBdField(bdField);
    }
    
    public void StudentDataOnDemand.setBdUniversity(Student obj, int index) {
        String bdUniversity = "bdUniversity_" + index;
        obj.setBdUniversity(bdUniversity);
    }
    
    public void StudentDataOnDemand.setBdYear(Student obj, int index) {
        String bdYear = "bdYear_" + index;
        obj.setBdYear(bdYear);
    }
    
    public void StudentDataOnDemand.setBdateString(Student obj, int index) {
        String bdateString = "bdateString_" + index;
        obj.setBdateString(bdateString);
    }
    
    public void StudentDataOnDemand.setBeefFood(Student obj, int index) {
        Boolean beefFood = true;
        obj.setBeefFood(beefFood);
    }
    
    public void StudentDataOnDemand.setBirthdate(Student obj, int index) {
        Date birthdate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setBirthdate(birthdate);
    }
    
    public void StudentDataOnDemand.setBuilding(Student obj, int index) {
        String building = "building_" + index;
        obj.setBuilding(building);
    }
    
    public void StudentDataOnDemand.setCarBrand(Student obj, int index) {
        String carBrand = "carBrand_" + index;
        obj.setCarBrand(carBrand);
    }
    
    public void StudentDataOnDemand.setCarColor(Student obj, int index) {
        String carColor = "carColor_" + index;
        obj.setCarColor(carColor);
    }
    
    public void StudentDataOnDemand.setCarNo(Student obj, int index) {
        String carNo = "carNo_" + index;
        obj.setCarNo(carNo);
    }
    
    public void StudentDataOnDemand.setChildrenBdateString(Student obj, int index) {
        String childrenBdateString = "childrenBdateString_" + index;
        obj.setChildrenBdateString(childrenBdateString);
    }
    
    public void StudentDataOnDemand.setChildrenBirthday(Student obj, int index) {
        Date childrenBirthday = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setChildrenBirthday(childrenBirthday);
    }
    
    public void StudentDataOnDemand.setChildrenCareer(Student obj, int index) {
        String childrenCareer = "childrenCareer_" + index;
        obj.setChildrenCareer(childrenCareer);
    }
    
    public void StudentDataOnDemand.setChildrenFirstName(Student obj, int index) {
        String childrenFirstName = "childrenFirstName_" + index;
        obj.setChildrenFirstName(childrenFirstName);
    }
    
    public void StudentDataOnDemand.setChildrenLastName(Student obj, int index) {
        String childrenLastName = "childrenLastName_" + index;
        obj.setChildrenLastName(childrenLastName);
    }
    
    public void StudentDataOnDemand.setChildrenNationality(Student obj, int index) {
        String childrenNationality = "childrenNationality_" + index;
        obj.setChildrenNationality(childrenNationality);
    }
    
    public void StudentDataOnDemand.setChildrenRace(Student obj, int index) {
        String childrenRace = "childrenRace_" + index;
        obj.setChildrenRace(childrenRace);
    }
    
    public void StudentDataOnDemand.setChildrenReligion(Student obj, int index) {
        String childrenReligion = "childrenReligion_" + index;
        obj.setChildrenReligion(childrenReligion);
    }
    
    public void StudentDataOnDemand.setCollboratorEmail(Student obj, int index) {
        String collboratorEmail = "foo" + index + "@bar.com";
        obj.setCollboratorEmail(collboratorEmail);
    }
    
    public void StudentDataOnDemand.setCollboratorFax(Student obj, int index) {
        String collboratorFax = "collboratorFax_" + index;
        obj.setCollboratorFax(collboratorFax);
    }
    
    public void StudentDataOnDemand.setCollboratorFirstName(Student obj, int index) {
        String collboratorFirstName = "collboratorFirstName_" + index;
        obj.setCollboratorFirstName(collboratorFirstName);
    }
    
    public void StudentDataOnDemand.setCollboratorFullName(Student obj, int index) {
        String collboratorFullName = "collboratorFullName_" + index;
        obj.setCollboratorFullName(collboratorFullName);
    }
    
    public void StudentDataOnDemand.setCollboratorLastName(Student obj, int index) {
        String collboratorLastName = "collboratorLastName_" + index;
        obj.setCollboratorLastName(collboratorLastName);
    }
    
    public void StudentDataOnDemand.setCollboratorLineId(Student obj, int index) {
        String collboratorLineId = "collboratorLineId_" + index;
        obj.setCollboratorLineId(collboratorLineId);
    }
    
    public void StudentDataOnDemand.setCollboratorMobile(Student obj, int index) {
        String collboratorMobile = "collboratorMobile_" + index;
        obj.setCollboratorMobile(collboratorMobile);
    }
    
    public void StudentDataOnDemand.setCollboratorPosition(Student obj, int index) {
        String collboratorPosition = "collboratorPosition_" + index;
        obj.setCollboratorPosition(collboratorPosition);
    }
    
    public void StudentDataOnDemand.setCollboratorTel(Student obj, int index) {
        String collboratorTel = "collboratorTel_" + index;
        obj.setCollboratorTel(collboratorTel);
    }
    
    public void StudentDataOnDemand.setCollboratorTel_2(Student obj, int index) {
        String collboratorTel_2 = "collboratorTel_2_" + index;
        obj.setCollboratorTel_2(collboratorTel_2);
    }
    
    public void StudentDataOnDemand.setCollboratorTitle(Student obj, int index) {
        String collboratorTitle = "collboratorTitle_" + index;
        obj.setCollboratorTitle(collboratorTitle);
    }
    
    public void StudentDataOnDemand.setDataState(Student obj, int index) {
        String dataState = "dataState_" + index;
        obj.setDataState(dataState);
    }
    
    public void StudentDataOnDemand.setDistrict(Student obj, int index) {
        String district = "district_" + index;
        obj.setDistrict(district);
    }
    
    public void StudentDataOnDemand.setDriverTel(Student obj, int index) {
        String driverTel = "driverTel_" + index;
        obj.setDriverTel(driverTel);
    }
    
    public void StudentDataOnDemand.setEmail(Student obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void StudentDataOnDemand.setEmail2(Student obj, int index) {
        String email2 = "foo" + index + "@bar.com";
        obj.setEmail2(email2);
    }
    
    public void StudentDataOnDemand.setEnrollType(Student obj, int index) {
        String enrollType = "enrollType_" + index;
        obj.setEnrollType(enrollType);
    }
    
    public void StudentDataOnDemand.setExtcollboratorTel(Student obj, int index) {
        String extcollboratorTel = "extcollboratorTel_" + index;
        obj.setExtcollboratorTel(extcollboratorTel);
    }
    
    public void StudentDataOnDemand.setExthometel1(Student obj, int index) {
        String exthometel1 = "exthometel1_" + index;
        obj.setExthometel1(exthometel1);
    }
    
    public void StudentDataOnDemand.setExthometel2(Student obj, int index) {
        String exthometel2 = "exthometel2_" + index;
        obj.setExthometel2(exthometel2);
    }
    
    public void StudentDataOnDemand.setExtworktel1(Student obj, int index) {
        String extworktel1 = "extworktel1_" + index;
        obj.setExtworktel1(extworktel1);
    }
    
    public void StudentDataOnDemand.setExtworktel2(Student obj, int index) {
        String extworktel2 = "extworktel2_" + index;
        obj.setExtworktel2(extworktel2);
    }
    
    public void StudentDataOnDemand.setFacebook(Student obj, int index) {
        String facebook = "facebook_" + index;
        obj.setFacebook(facebook);
    }
    
    public void StudentDataOnDemand.setFirstnameEn(Student obj, int index) {
        String firstnameEn = "firstnameEn_" + index;
        obj.setFirstnameEn(firstnameEn);
    }
    
    public void StudentDataOnDemand.setFirstnameTh(Student obj, int index) {
        String firstnameTh = "firstnameTh_" + index;
        obj.setFirstnameTh(firstnameTh);
    }
    
    public void StudentDataOnDemand.setFloor(Student obj, int index) {
        String floor = "floor_" + index;
        obj.setFloor(floor);
    }
    
    public void StudentDataOnDemand.setFrontcollboratorFax(Student obj, int index) {
        String frontcollboratorFax = "frontcollboratorFax_" + index;
        obj.setFrontcollboratorFax(frontcollboratorFax);
    }
    
    public void StudentDataOnDemand.setFrontcollboratorMobile(Student obj, int index) {
        String frontcollboratorMobile = "frontcollboratorMobile_" + index;
        obj.setFrontcollboratorMobile(frontcollboratorMobile);
    }
    
    public void StudentDataOnDemand.setFrontcollboratorTel(Student obj, int index) {
        String frontcollboratorTel = "frontcollboratorTel_" + index;
        obj.setFrontcollboratorTel(frontcollboratorTel);
    }
    
    public void StudentDataOnDemand.setFrontdriverTel(Student obj, int index) {
        String frontdriverTel = "frontdriverTel_" + index;
        obj.setFrontdriverTel(frontdriverTel);
    }
    
    public void StudentDataOnDemand.setFronthomefax(Student obj, int index) {
        String fronthomefax = "fronthomefax_" + index;
        obj.setFronthomefax(fronthomefax);
    }
    
    public void StudentDataOnDemand.setFronthometel1(Student obj, int index) {
        String fronthometel1 = "fronthometel1_" + index;
        obj.setFronthometel1(fronthometel1);
    }
    
    public void StudentDataOnDemand.setFronthometel2(Student obj, int index) {
        String fronthometel2 = "fronthometel2_" + index;
        obj.setFronthometel2(fronthometel2);
    }
    
    public void StudentDataOnDemand.setFrontmobile1(Student obj, int index) {
        String frontmobile1 = "frontmobile1_" + index;
        obj.setFrontmobile1(frontmobile1);
    }
    
    public void StudentDataOnDemand.setFrontmobile2(Student obj, int index) {
        String frontmobile2 = "frontmobile2_" + index;
        obj.setFrontmobile2(frontmobile2);
    }
    
    public void StudentDataOnDemand.setFrontworkfax(Student obj, int index) {
        String frontworkfax = "frontworkfax_" + index;
        obj.setFrontworkfax(frontworkfax);
    }
    
    public void StudentDataOnDemand.setFrontworktel1(Student obj, int index) {
        String frontworktel1 = "frontworktel1_" + index;
        obj.setFrontworktel1(frontworktel1);
    }
    
    public void StudentDataOnDemand.setFrontworktel2(Student obj, int index) {
        String frontworktel2 = "frontworktel2_" + index;
        obj.setFrontworktel2(frontworktel2);
    }
    
    public void StudentDataOnDemand.setFullNameEn(Student obj, int index) {
        String fullNameEn = "fullNameEn_" + index;
        obj.setFullNameEn(fullNameEn);
    }
    
    public void StudentDataOnDemand.setFullNameTh(Student obj, int index) {
        String fullNameTh = "fullNameTh_" + index;
        obj.setFullNameTh(fullNameTh);
    }
    
    public void StudentDataOnDemand.setGeneralFood(Student obj, int index) {
        Boolean generalFood = true;
        obj.setGeneralFood(generalFood);
    }
    
    public void StudentDataOnDemand.setGroupName(Student obj, int index) {
        String groupName = "groupName_" + index;
        obj.setGroupName(groupName);
    }
    
    public void StudentDataOnDemand.setHalalFood(Student obj, int index) {
        Boolean halalFood = true;
        obj.setHalalFood(halalFood);
    }
    
    public void StudentDataOnDemand.setHandyCap(Student obj, int index) {
        String handyCap = "handyCap_" + index;
        obj.setHandyCap(handyCap);
    }
    
    public void StudentDataOnDemand.setHomeFullAddress(Student obj, int index) {
        String homeFullAddress = "homeFullAddress_" + index;
        obj.setHomeFullAddress(homeFullAddress);
    }
    
    public void StudentDataOnDemand.setHomeNo(Student obj, int index) {
        String homeNo = "homeNo_" + index;
        obj.setHomeNo(homeNo);
    }
    
    public void StudentDataOnDemand.setHomefax(Student obj, int index) {
        String homefax = "homefax_" + index;
        obj.setHomefax(homefax);
    }
    
    public void StudentDataOnDemand.setHometel1(Student obj, int index) {
        String hometel1 = "hometel1_" + index;
        obj.setHometel1(hometel1);
    }
    
    public void StudentDataOnDemand.setHometel1_2(Student obj, int index) {
        String hometel1_2 = "hometel1_2_" + index;
        obj.setHometel1_2(hometel1_2);
    }
    
    public void StudentDataOnDemand.setHometel2(Student obj, int index) {
        String hometel2 = "hometel2_" + index;
        obj.setHometel2(hometel2);
    }
    
    public void StudentDataOnDemand.setHometel2_2(Student obj, int index) {
        String hometel2_2 = "hometel2_2_" + index;
        obj.setHometel2_2(hometel2_2);
    }
    
    public void StudentDataOnDemand.setIdcardNo(Student obj, int index) {
        String idcardNo = "idcardNo_" + index;
        obj.setIdcardNo(idcardNo);
    }
    
    public void StudentDataOnDemand.setInstitutionBuilding(Student obj, int index) {
        String institutionBuilding = "institutionBuilding_" + index;
        obj.setInstitutionBuilding(institutionBuilding);
    }
    
    public void StudentDataOnDemand.setInstitutionDistrict(Student obj, int index) {
        String institutionDistrict = "institutionDistrict_" + index;
        obj.setInstitutionDistrict(institutionDistrict);
    }
    
    public void StudentDataOnDemand.setInstitutionEn(Student obj, int index) {
        String institutionEn = "institutionEn_" + index;
        obj.setInstitutionEn(institutionEn);
    }
    
    public void StudentDataOnDemand.setInstitutionFloor(Student obj, int index) {
        String institutionFloor = "institutionFloor_" + index;
        obj.setInstitutionFloor(institutionFloor);
    }
    
    public void StudentDataOnDemand.setInstitutionMooNo(Student obj, int index) {
        String institutionMooNo = "institutionMooNo_" + index;
        obj.setInstitutionMooNo(institutionMooNo);
    }
    
    public void StudentDataOnDemand.setInstitutionNo(Student obj, int index) {
        String institutionNo = "institutionNo_" + index;
        obj.setInstitutionNo(institutionNo);
    }
    
    public void StudentDataOnDemand.setInstitutionPostalCode(Student obj, int index) {
        String institutionPostalCode = "institutionPostalCode_" + index;
        obj.setInstitutionPostalCode(institutionPostalCode);
    }
    
    public void StudentDataOnDemand.setInstitutionProvince(Student obj, int index) {
        String institutionProvince = "institutionProvince_" + index;
        obj.setInstitutionProvince(institutionProvince);
    }
    
    public void StudentDataOnDemand.setInstitutionSoi(Student obj, int index) {
        String institutionSoi = "institutionSoi_" + index;
        obj.setInstitutionSoi(institutionSoi);
    }
    
    public void StudentDataOnDemand.setInstitutionStreet(Student obj, int index) {
        String institutionStreet = "institutionStreet_" + index;
        obj.setInstitutionStreet(institutionStreet);
    }
    
    public void StudentDataOnDemand.setInstitutionSubdistrict(Student obj, int index) {
        String institutionSubdistrict = "institutionSubdistrict_" + index;
        obj.setInstitutionSubdistrict(institutionSubdistrict);
    }
    
    public void StudentDataOnDemand.setInstitutionTh(Student obj, int index) {
        String institutionTh = "institutionTh_" + index;
        obj.setInstitutionTh(institutionTh);
    }
    
    public void StudentDataOnDemand.setJFood(Student obj, int index) {
        Boolean jFood = true;
        obj.setJFood(jFood);
    }
    
    public void StudentDataOnDemand.setJacketSize(Student obj, int index) {
        String jacketSize = "jacketSize_" + index;
        obj.setJacketSize(jacketSize);
    }
    
    public void StudentDataOnDemand.setLastcollboratorFax(Student obj, int index) {
        String lastcollboratorFax = "lastcollboratorFax_" + index;
        obj.setLastcollboratorFax(lastcollboratorFax);
    }
    
    public void StudentDataOnDemand.setLastcollboratorMobile(Student obj, int index) {
        String lastcollboratorMobile = "lastcollboratorMobile_" + index;
        obj.setLastcollboratorMobile(lastcollboratorMobile);
    }
    
    public void StudentDataOnDemand.setLastcollboratorTel(Student obj, int index) {
        String lastcollboratorTel = "lastcollboratorTel_" + index;
        obj.setLastcollboratorTel(lastcollboratorTel);
    }
    
    public void StudentDataOnDemand.setLastdriverTel(Student obj, int index) {
        String lastdriverTel = "lastdriverTel_" + index;
        obj.setLastdriverTel(lastdriverTel);
    }
    
    public void StudentDataOnDemand.setLasthomefax(Student obj, int index) {
        String lasthomefax = "lasthomefax_" + index;
        obj.setLasthomefax(lasthomefax);
    }
    
    public void StudentDataOnDemand.setLasthometel1(Student obj, int index) {
        String lasthometel1 = "lasthometel1_" + index;
        obj.setLasthometel1(lasthometel1);
    }
    
    public void StudentDataOnDemand.setLasthometel2(Student obj, int index) {
        String lasthometel2 = "lasthometel2_" + index;
        obj.setLasthometel2(lasthometel2);
    }
    
    public void StudentDataOnDemand.setLastmobile1(Student obj, int index) {
        String lastmobile1 = "lastmobile1_" + index;
        obj.setLastmobile1(lastmobile1);
    }
    
    public void StudentDataOnDemand.setLastmobile2(Student obj, int index) {
        String lastmobile2 = "lastmobile2_" + index;
        obj.setLastmobile2(lastmobile2);
    }
    
    public void StudentDataOnDemand.setLastnameEn(Student obj, int index) {
        String lastnameEn = "lastnameEn_" + index;
        obj.setLastnameEn(lastnameEn);
    }
    
    public void StudentDataOnDemand.setLastnameTh(Student obj, int index) {
        String lastnameTh = "lastnameTh_" + index;
        obj.setLastnameTh(lastnameTh);
    }
    
    public void StudentDataOnDemand.setLastworkfax(Student obj, int index) {
        String lastworkfax = "lastworkfax_" + index;
        obj.setLastworkfax(lastworkfax);
    }
    
    public void StudentDataOnDemand.setLastworktel1(Student obj, int index) {
        String lastworktel1 = "lastworktel1_" + index;
        obj.setLastworktel1(lastworktel1);
    }
    
    public void StudentDataOnDemand.setLastworktel2(Student obj, int index) {
        String lastworktel2 = "lastworktel2_" + index;
        obj.setLastworktel2(lastworktel2);
    }
    
    public void StudentDataOnDemand.setLineId(Student obj, int index) {
        String lineId = "lineId_" + index;
        obj.setLineId(lineId);
    }
    
    public void StudentDataOnDemand.setMarriedStatus(Student obj, int index) {
        String marriedStatus = "marriedStatus_" + index;
        obj.setMarriedStatus(marriedStatus);
    }
    
    public void StudentDataOnDemand.setMdField(Student obj, int index) {
        String mdField = "mdField_" + index;
        obj.setMdField(mdField);
    }
    
    public void StudentDataOnDemand.setMdUniversity(Student obj, int index) {
        String mdUniversity = "mdUniversity_" + index;
        obj.setMdUniversity(mdUniversity);
    }
    
    public void StudentDataOnDemand.setMdYear(Student obj, int index) {
        String mdYear = "mdYear_" + index;
        obj.setMdYear(mdYear);
    }
    
    public void StudentDataOnDemand.setMiddlecollboratorFax(Student obj, int index) {
        String middlecollboratorFax = "middlecollboratorFax_" + index;
        obj.setMiddlecollboratorFax(middlecollboratorFax);
    }
    
    public void StudentDataOnDemand.setMiddlecollboratorMobile(Student obj, int index) {
        String middlecollboratorMobile = "middlecollboratorMobile_" + index;
        obj.setMiddlecollboratorMobile(middlecollboratorMobile);
    }
    
    public void StudentDataOnDemand.setMiddlecollboratorTel(Student obj, int index) {
        String middlecollboratorTel = "middlecollboratorTel_" + index;
        obj.setMiddlecollboratorTel(middlecollboratorTel);
    }
    
    public void StudentDataOnDemand.setMiddledriverTel(Student obj, int index) {
        String middledriverTel = "middledriverTel_" + index;
        obj.setMiddledriverTel(middledriverTel);
    }
    
    public void StudentDataOnDemand.setMiddlehomefax(Student obj, int index) {
        String middlehomefax = "middlehomefax_" + index;
        obj.setMiddlehomefax(middlehomefax);
    }
    
    public void StudentDataOnDemand.setMiddlehometel1(Student obj, int index) {
        String middlehometel1 = "middlehometel1_" + index;
        obj.setMiddlehometel1(middlehometel1);
    }
    
    public void StudentDataOnDemand.setMiddlehometel2(Student obj, int index) {
        String middlehometel2 = "middlehometel2_" + index;
        obj.setMiddlehometel2(middlehometel2);
    }
    
    public void StudentDataOnDemand.setMiddlemobile1(Student obj, int index) {
        String middlemobile1 = "middlemobile1_" + index;
        obj.setMiddlemobile1(middlemobile1);
    }
    
    public void StudentDataOnDemand.setMiddlemobile2(Student obj, int index) {
        String middlemobile2 = "middlemobile2_" + index;
        obj.setMiddlemobile2(middlemobile2);
    }
    
    public void StudentDataOnDemand.setMiddleworkfax(Student obj, int index) {
        String middleworkfax = "middleworkfax_" + index;
        obj.setMiddleworkfax(middleworkfax);
    }
    
    public void StudentDataOnDemand.setMiddleworktel1(Student obj, int index) {
        String middleworktel1 = "middleworktel1_" + index;
        obj.setMiddleworktel1(middleworktel1);
    }
    
    public void StudentDataOnDemand.setMiddleworktel2(Student obj, int index) {
        String middleworktel2 = "middleworktel2_" + index;
        obj.setMiddleworktel2(middleworktel2);
    }
    
    public void StudentDataOnDemand.setMobile1(Student obj, int index) {
        String mobile1 = "mobile1_" + index;
        obj.setMobile1(mobile1);
    }
    
    public void StudentDataOnDemand.setMobile2(Student obj, int index) {
        String mobile2 = "mobile2_" + index;
        obj.setMobile2(mobile2);
    }
    
    public void StudentDataOnDemand.setMooNo(Student obj, int index) {
        String mooNo = "mooNo_" + index;
        obj.setMooNo(mooNo);
    }
    
    public void StudentDataOnDemand.setNickname(Student obj, int index) {
        String nickname = "nickname_" + index;
        obj.setNickname(nickname);
    }
    
    public void StudentDataOnDemand.setOtherFood(Student obj, int index) {
        String otherFood = "otherFood_" + index;
        obj.setOtherFood(otherFood);
    }
    
    public void StudentDataOnDemand.setPassportNo(Student obj, int index) {
        String passportNo = "passportNo_" + index;
        obj.setPassportNo(passportNo);
    }
    
    public void StudentDataOnDemand.setPermission(Student obj, int index) {
        Integer permission = new Integer(index);
        obj.setPermission(permission);
    }
    
    public void StudentDataOnDemand.setPhdField(Student obj, int index) {
        String phdField = "phdField_" + index;
        obj.setPhdField(phdField);
    }
    
    public void StudentDataOnDemand.setPhdUniversity(Student obj, int index) {
        String phdUniversity = "phdUniversity_" + index;
        obj.setPhdUniversity(phdUniversity);
    }
    
    public void StudentDataOnDemand.setPhdYear(Student obj, int index) {
        String phdYear = "phdYear_" + index;
        obj.setPhdYear(phdYear);
    }
    
    public void StudentDataOnDemand.setPhotoFileName(Student obj, int index) {
        String photoFileName = "photoFileName_" + index;
        obj.setPhotoFileName(photoFileName);
    }
    
    public void StudentDataOnDemand.setPlayGolf(Student obj, int index) {
        String playGolf = "playGolf_" + index;
        obj.setPlayGolf(playGolf);
    }
    
    public void StudentDataOnDemand.setPoloSize(Student obj, int index) {
        String poloSize = "poloSize_" + index;
        obj.setPoloSize(poloSize);
    }
    
    public void StudentDataOnDemand.setPositionEn(Student obj, int index) {
        String positionEn = "positionEn_" + index;
        obj.setPositionEn(positionEn);
    }
    
    public void StudentDataOnDemand.setPositionTh(Student obj, int index) {
        String positionTh = "positionTh_" + index;
        obj.setPositionTh(positionTh);
    }
    
    public void StudentDataOnDemand.setPostalCode(Student obj, int index) {
        String postalCode = "postalCode_" + index;
        obj.setPostalCode(postalCode);
    }
    
    public void StudentDataOnDemand.setProvince(Student obj, int index) {
        String province = "province_" + index;
        obj.setProvince(province);
    }
    
    public void StudentDataOnDemand.setReceiptDetailAddress(Student obj, int index) {
        String receiptDetailAddress = "receiptDetailAddress_" + index;
        obj.setReceiptDetailAddress(receiptDetailAddress);
    }
    
    public void StudentDataOnDemand.setReceiptDetailName(Student obj, int index) {
        String receiptDetailName = "receiptDetailName_" + index;
        obj.setReceiptDetailName(receiptDetailName);
    }
    
    public void StudentDataOnDemand.setRetireFlag(Student obj, int index) {
        Boolean retireFlag = true;
        obj.setRetireFlag(retireFlag);
    }
    
    public void StudentDataOnDemand.setRopNo(Student obj, int index) {
        String ropNo = "ropNo_" + index;
        obj.setRopNo(ropNo);
    }
    
    public void StudentDataOnDemand.setSendingAddress(Student obj, int index) {
        String sendingAddress = "sendingAddress_" + index;
        obj.setSendingAddress(sendingAddress);
    }
    
    public void StudentDataOnDemand.setSex(Student obj, int index) {
        String sex = "sex_" + index;
        obj.setSex(sex);
    }
    
    public void StudentDataOnDemand.setSmoking(Student obj, int index) {
        String smoking = "smoking_" + index;
        obj.setSmoking(smoking);
    }
    
    public void StudentDataOnDemand.setSoi(Student obj, int index) {
        String soi = "soi_" + index;
        obj.setSoi(soi);
    }
    
    public void StudentDataOnDemand.setSpouseBdateString(Student obj, int index) {
        String spouseBdateString = "spouseBdateString_" + index;
        obj.setSpouseBdateString(spouseBdateString);
    }
    
    public void StudentDataOnDemand.setSpouseBirthDay(Student obj, int index) {
        Date spouseBirthDay = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setSpouseBirthDay(spouseBirthDay);
    }
    
    public void StudentDataOnDemand.setSpouseCareer(Student obj, int index) {
        String spouseCareer = "spouseCareer_" + index;
        obj.setSpouseCareer(spouseCareer);
    }
    
    public void StudentDataOnDemand.setSpouseFirstName(Student obj, int index) {
        String spouseFirstName = "spouseFirstName_" + index;
        obj.setSpouseFirstName(spouseFirstName);
    }
    
    public void StudentDataOnDemand.setSpouseInstitution(Student obj, int index) {
        String spouseInstitution = "spouseInstitution_" + index;
        obj.setSpouseInstitution(spouseInstitution);
    }
    
    public void StudentDataOnDemand.setSpouseLastName(Student obj, int index) {
        String spouseLastName = "spouseLastName_" + index;
        obj.setSpouseLastName(spouseLastName);
    }
    
    public void StudentDataOnDemand.setSpouseNationality(Student obj, int index) {
        String spouseNationality = "spouseNationality_" + index;
        obj.setSpouseNationality(spouseNationality);
    }
    
    public void StudentDataOnDemand.setSpouseRace(Student obj, int index) {
        String spouseRace = "spouseRace_" + index;
        obj.setSpouseRace(spouseRace);
    }
    
    public void StudentDataOnDemand.setSpouseReligion(Student obj, int index) {
        String spouseReligion = "spouseReligion_" + index;
        obj.setSpouseReligion(spouseReligion);
    }
    
    public void StudentDataOnDemand.setStreet(Student obj, int index) {
        String street = "street_" + index;
        obj.setStreet(street);
    }
    
    public void StudentDataOnDemand.setStudentClass(Student obj, int index) {
        Batch studentClass = null;
        obj.setStudentClass(studentClass);
    }
    
    public void StudentDataOnDemand.setSubdistrict(Student obj, int index) {
        String subdistrict = "subdistrict_" + index;
        obj.setSubdistrict(subdistrict);
    }
    
    public void StudentDataOnDemand.setSubmitProfile(Student obj, int index) {
        Boolean submitProfile = Boolean.TRUE;
        obj.setSubmitProfile(submitProfile);
    }
    
    public void StudentDataOnDemand.setTall(Student obj, int index) {
        String tall = "tall_" + index;
        obj.setTall(tall);
    }
    
    public void StudentDataOnDemand.setTaxId(Student obj, int index) {
        String taxId = "taxId_" + index;
        obj.setTaxId(taxId);
    }
    
    public void StudentDataOnDemand.setTitleEn(Student obj, int index) {
        String titleEn = "titleEn_" + index;
        obj.setTitleEn(titleEn);
    }
    
    public void StudentDataOnDemand.setTitleTh(Student obj, int index) {
        String titleTh = "titleTh_" + index;
        obj.setTitleTh(titleTh);
    }
    
    public void StudentDataOnDemand.setTraingYear(Student obj, int index) {
        String traingYear = "traingYear_" + index;
        obj.setTraingYear(traingYear);
    }
    
    public void StudentDataOnDemand.setTrainingClass(Student obj, int index) {
        String trainingClass = "trainingClass_" + index;
        obj.setTrainingClass(trainingClass);
    }
    
    public void StudentDataOnDemand.setTrainingInstitute(Student obj, int index) {
        String trainingInstitute = "trainingInstitute_" + index;
        obj.setTrainingInstitute(trainingInstitute);
    }
    
    public void StudentDataOnDemand.setTrainingName(Student obj, int index) {
        String trainingName = "trainingName_" + index;
        obj.setTrainingName(trainingName);
    }
    
    public void StudentDataOnDemand.setUserWeb(Student obj, int index) {
        UserWeb userWeb = null;
        obj.setUserWeb(userWeb);
    }
    
    public void StudentDataOnDemand.setVegeterianFood(Student obj, int index) {
        Boolean vegeterianFood = true;
        obj.setVegeterianFood(vegeterianFood);
    }
    
    public void StudentDataOnDemand.setVillage(Student obj, int index) {
        String village = "village_" + index;
        obj.setVillage(village);
    }
    
    public void StudentDataOnDemand.setWaist(Student obj, int index) {
        String waist = "waist_" + index;
        obj.setWaist(waist);
    }
    
    public void StudentDataOnDemand.setWorkEmail(Student obj, int index) {
        String workEmail = "foo" + index + "@bar.com";
        obj.setWorkEmail(workEmail);
    }
    
    public void StudentDataOnDemand.setWorkFullAddress(Student obj, int index) {
        String workFullAddress = "workFullAddress_" + index;
        obj.setWorkFullAddress(workFullAddress);
    }
    
    public void StudentDataOnDemand.setWorkfax(Student obj, int index) {
        String workfax = "workfax_" + index;
        obj.setWorkfax(workfax);
    }
    
    public void StudentDataOnDemand.setWorktel1(Student obj, int index) {
        String worktel1 = "worktel1_" + index;
        obj.setWorktel1(worktel1);
    }
    
    public void StudentDataOnDemand.setWorktel1_2(Student obj, int index) {
        String worktel1_2 = "worktel1_2_" + index;
        obj.setWorktel1_2(worktel1_2);
    }
    
    public void StudentDataOnDemand.setWorktel2(Student obj, int index) {
        String worktel2 = "worktel2_" + index;
        obj.setWorktel2(worktel2);
    }
    
    public void StudentDataOnDemand.setWorktel2_2(Student obj, int index) {
        String worktel2_2 = "worktel2_2_" + index;
        obj.setWorktel2_2(worktel2_2);
    }
    
    public Student StudentDataOnDemand.getSpecificStudent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Student obj = data.get(index);
        Long id = obj.getId();
        return Student.findStudent(id);
    }
    
    public Student StudentDataOnDemand.getRandomStudent() {
        init();
        Student obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Student.findStudent(id);
    }
    
    public boolean StudentDataOnDemand.modifyStudent(Student obj) {
        return false;
    }
    
    public void StudentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Student.findStudentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Student' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Student>();
        for (int i = 0; i < 10; i++) {
            Student obj = getNewTransientStudent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
