// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.UserRegisRole;
import com.cma.UserRegisRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserRegisRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserRegisRoleDataOnDemand: @Component;
    
    private Random UserRegisRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<UserRegisRole> UserRegisRoleDataOnDemand.data;
    
    public UserRegisRole UserRegisRoleDataOnDemand.getNewTransientUserRegisRole(int index) {
        UserRegisRole obj = new UserRegisRole();
        setRole_name(obj, index);
        return obj;
    }
    
    public void UserRegisRoleDataOnDemand.setRole_name(UserRegisRole obj, int index) {
        String role_name = "role_name_" + index;
        obj.setRole_name(role_name);
    }
    
    public UserRegisRole UserRegisRoleDataOnDemand.getSpecificUserRegisRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserRegisRole obj = data.get(index);
        Long id = obj.getId();
        return UserRegisRole.findUserRegisRole(id);
    }
    
    public UserRegisRole UserRegisRoleDataOnDemand.getRandomUserRegisRole() {
        init();
        UserRegisRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserRegisRole.findUserRegisRole(id);
    }
    
    public boolean UserRegisRoleDataOnDemand.modifyUserRegisRole(UserRegisRole obj) {
        return false;
    }
    
    public void UserRegisRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserRegisRole.findUserRegisRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserRegisRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserRegisRole>();
        for (int i = 0; i < 10; i++) {
            UserRegisRole obj = getNewTransientUserRegisRole(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
