// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.UserWeb;
import com.cma.UserWebRole;
import com.cma.UserWebRoleDataOnDemand;
import com.cma.WebRole;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserWebRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserWebRoleDataOnDemand: @Component;
    
    private Random UserWebRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<UserWebRole> UserWebRoleDataOnDemand.data;
    
    public UserWebRole UserWebRoleDataOnDemand.getNewTransientUserWebRole(int index) {
        UserWebRole obj = new UserWebRole();
        setUserWeb(obj, index);
        setWebRole(obj, index);
        return obj;
    }
    
    public void UserWebRoleDataOnDemand.setUserWeb(UserWebRole obj, int index) {
        UserWeb userWeb = null;
        obj.setUserWeb(userWeb);
    }
    
    public void UserWebRoleDataOnDemand.setWebRole(UserWebRole obj, int index) {
        WebRole webRole = null;
        obj.setWebRole(webRole);
    }
    
    public UserWebRole UserWebRoleDataOnDemand.getSpecificUserWebRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserWebRole obj = data.get(index);
        Long id = obj.getUser_id();
        return UserWebRole.findUserWebRole(id);
    }
    
    public UserWebRole UserWebRoleDataOnDemand.getRandomUserWebRole() {
        init();
        UserWebRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getUser_id();
        return UserWebRole.findUserWebRole(id);
    }
    
    public boolean UserWebRoleDataOnDemand.modifyUserWebRole(UserWebRole obj) {
        return false;
    }
    
    public void UserWebRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserWebRole.findUserWebRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserWebRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserWebRole>();
        for (int i = 0; i < 10; i++) {
            UserWebRole obj = getNewTransientUserWebRole(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
