// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.UserWeb;
import com.cma.UserWebDataOnDemand;
import com.cma.UserWebIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserWebIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserWebIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserWebIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserWebIntegrationTest: @Transactional;
    
    @Autowired
    UserWebDataOnDemand UserWebIntegrationTest.dod;
    
    @Test
    public void UserWebIntegrationTest.testCountUserWebs() {
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", dod.getRandomUserWeb());
        long count = UserWeb.countUserWebs();
        Assert.assertTrue("Counter for 'UserWeb' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserWebIntegrationTest.testFindUserWeb() {
        UserWeb obj = dod.getRandomUserWeb();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to provide an identifier", id);
        obj = UserWeb.findUserWeb(id);
        Assert.assertNotNull("Find method for 'UserWeb' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserWeb' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserWebIntegrationTest.testFindAllUserWebs() {
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", dod.getRandomUserWeb());
        long count = UserWeb.countUserWebs();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserWeb', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserWeb> result = UserWeb.findAllUserWebs();
        Assert.assertNotNull("Find all method for 'UserWeb' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserWeb' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserWebIntegrationTest.testFindUserWebEntries() {
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", dod.getRandomUserWeb());
        long count = UserWeb.countUserWebs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserWeb> result = UserWeb.findUserWebEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserWeb' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserWeb' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserWebIntegrationTest.testFlush() {
        UserWeb obj = dod.getRandomUserWeb();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to provide an identifier", id);
        obj = UserWeb.findUserWeb(id);
        Assert.assertNotNull("Find method for 'UserWeb' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserWeb(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserWeb' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserWebIntegrationTest.testMergeUpdate() {
        UserWeb obj = dod.getRandomUserWeb();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to provide an identifier", id);
        obj = UserWeb.findUserWeb(id);
        boolean modified =  dod.modifyUserWeb(obj);
        Integer currentVersion = obj.getVersion();
        UserWeb merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserWeb' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserWebIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", dod.getRandomUserWeb());
        UserWeb obj = dod.getNewTransientUserWeb(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserWeb' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserWeb' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserWebIntegrationTest.testRemove() {
        UserWeb obj = dod.getRandomUserWeb();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserWeb' failed to provide an identifier", id);
        obj = UserWeb.findUserWeb(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserWeb' with identifier '" + id + "'", UserWeb.findUserWeb(id));
    }
    
}
