// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.WebRole;
import com.cma.WebRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WebRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WebRoleDataOnDemand: @Component;
    
    private Random WebRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<WebRole> WebRoleDataOnDemand.data;
    
    public WebRole WebRoleDataOnDemand.getNewTransientWebRole(int index) {
        WebRole obj = new WebRole();
        setAuthority(obj, index);
        return obj;
    }
    
    public void WebRoleDataOnDemand.setAuthority(WebRole obj, int index) {
        String authority = "authority_" + index;
        obj.setAuthority(authority);
    }
    
    public WebRole WebRoleDataOnDemand.getSpecificWebRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WebRole obj = data.get(index);
        Long id = obj.getId();
        return WebRole.findWebRole(id);
    }
    
    public WebRole WebRoleDataOnDemand.getRandomWebRole() {
        init();
        WebRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WebRole.findWebRole(id);
    }
    
    public boolean WebRoleDataOnDemand.modifyWebRole(WebRole obj) {
        return false;
    }
    
    public void WebRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WebRole.findWebRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WebRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WebRole>();
        for (int i = 0; i < 10; i++) {
            WebRole obj = getNewTransientWebRole(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
