// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.WebRole;
import com.cma.WebRoleDataOnDemand;
import com.cma.WebRoleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WebRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WebRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WebRoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WebRoleIntegrationTest: @Transactional;
    
    @Autowired
    WebRoleDataOnDemand WebRoleIntegrationTest.dod;
    
    @Test
    public void WebRoleIntegrationTest.testCountWebRoles() {
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", dod.getRandomWebRole());
        long count = WebRole.countWebRoles();
        Assert.assertTrue("Counter for 'WebRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WebRoleIntegrationTest.testFindWebRole() {
        WebRole obj = dod.getRandomWebRole();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to provide an identifier", id);
        obj = WebRole.findWebRole(id);
        Assert.assertNotNull("Find method for 'WebRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WebRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WebRoleIntegrationTest.testFindAllWebRoles() {
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", dod.getRandomWebRole());
        long count = WebRole.countWebRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'WebRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WebRole> result = WebRole.findAllWebRoles();
        Assert.assertNotNull("Find all method for 'WebRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WebRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WebRoleIntegrationTest.testFindWebRoleEntries() {
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", dod.getRandomWebRole());
        long count = WebRole.countWebRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WebRole> result = WebRole.findWebRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WebRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WebRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WebRoleIntegrationTest.testFlush() {
        WebRole obj = dod.getRandomWebRole();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to provide an identifier", id);
        obj = WebRole.findWebRole(id);
        Assert.assertNotNull("Find method for 'WebRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWebRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WebRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WebRoleIntegrationTest.testMergeUpdate() {
        WebRole obj = dod.getRandomWebRole();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to provide an identifier", id);
        obj = WebRole.findWebRole(id);
        boolean modified =  dod.modifyWebRole(obj);
        Integer currentVersion = obj.getVersion();
        WebRole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WebRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WebRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", dod.getRandomWebRole());
        WebRole obj = dod.getNewTransientWebRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WebRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WebRole' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WebRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WebRoleIntegrationTest.testRemove() {
        WebRole obj = dod.getRandomWebRole();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WebRole' failed to provide an identifier", id);
        obj = WebRole.findWebRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WebRole' with identifier '" + id + "'", WebRole.findWebRole(id));
    }
    
}
