// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.MediaUpload;

privileged aspect MediaUpload_Roo_JavaBean {
    
    public byte[] MediaUpload.getContent() {
        return this.content;
    }
    
    public void MediaUpload.setContent(byte[] content) {
        this.content = content;
    }
    
}
