// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.Training_profile;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Training_profile_Roo_Configurable {
    
    declare @type: Training_profile: @Configurable;
    
}
