// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.UserRegisRole;

privileged aspect UserRegisRole_Roo_JavaBean {
    
    public String UserRegisRole.getRole_name() {
        return this.role_name;
    }
    
    public void UserRegisRole.setRole_name(String role_name) {
        this.role_name = role_name;
    }
    
}
