// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cma;

import com.cma.WebRole;

privileged aspect WebRole_Roo_JavaBean {
    
    public String WebRole.getAuthority() {
        return this.authority;
    }
    
    public void WebRole.setAuthority(String authority) {
        this.authority = authority;
    }
    
}
